# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request Build

on:
  pull_request:
    branches: [ master , main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: node publishBetaTags.js
    - run: cat package.json
    - run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
